# Generated by Django 2.2.7 on 2020-01-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200120_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='+2507445566667', max_length=15, unique=True),
        ),
    ]
