# Generated by Django 2.2.7 on 2020-01-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200120_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
